### ISSUE TITLE
[deps] ray, secretflow-ray, grpcio, Apple Silicon

### ISSUE THREAD

**Issue by tonywu6** [secretflow/secretnote#26]
https://github.com/secretflow/secretnote/blob/main/pyprojects/secretnote/pyproject.toml#L25-L26

There are unresolved issues with how we should specify requirements of `ray` and `secretflow-ray`. TODO:

**Comment by NewByVector** [comment]
secretflow 会在下周升级 secretflow-ray 到 ray，等 secretflow 升级后，我们直接依赖 ray 就可以了。
