### ISSUE TITLE
安装secretNote时候yaml: line 2: did not find expected key报错

### ISSUE THREAD

**Issue by momo-shen** [secretflow/secretnote#47]
在安装secretNote时新建了secretNote文件和在文件夹里面新建了yaml文件，运行docker compose up报错。
![5F8A5633@2E58B627 FD4C6466](https://github.com/secretflow/secretnote/assets/172120455/a0c6f45e-8736-4117-95a8-bbce9dee2a6a)

![image](https://github.com/secretflow/secretnote/assets/172120455/d80ede6e-85a3-48cc-a967-d22d1ae402d1)
yml文件中内容格式：
![image](https://github.com/secretflow/secretnote/assets/172120455/2cf0433e-ce55-48e9-91ca-1c237351afd7)

**Comment by momo-shen** [comment]
已经解决，应该是因为直接用vim编辑yml文件粘贴内容会产生格式错误，用自己的电脑新建了yml文件并粘贴内容，上传到Linux系统中，可以正常运行docker compose up
正常可以运行的格式如图：
![image](https://github.com/secretflow/secretnote/assets/172120455/f21bd911-3dfb-4afc-921d-a701f8e50246)

**Comment by kaixin-haha** [comment]
yaml格式问题，已解决
