### ISSUE TITLE
布署节点时即使使用不同的端口号仍然出现相同的错误，有没有老师或大神可以帮忙分析原因

### ISSUE THREAD

**Issue by zgrhld** [secretflow/secretnote#48]
<img width="936" alt="Snipaste_2024-07-07_17-02-10" src="https://github.com/secretflow/secretnote/assets/161600470/0cdb8372-dfca-4a54-b1e1-56a1af4ebb5c">
<img width="943" alt="Snipaste_2024-07-07_17-02-19" src="https://github.com/secretflow/secretnote/assets/161600470/b6987408-3711-498b-8bff-94a50ad4a234">

**Comment by zimu-yuxi** [comment]
secretflow版本是多少呢？>1.4.0b0，需要使用python 3.10

**Comment by zgrhld** [comment]
> secretflow版本是多少呢？>1.4.0b0，需要使用python 3.10
噢噢好的，感谢
