### ISSUE TITLE
镜像下载不下来

### ISSUE THREAD

**Issue by meijiesky** [secretflow/secretnote#51]
<img width="890" alt="Screenshot 2024-07-16 at 15 20 19" src="https://github.com/user-attachments/assets/0ea6e03e-ed71-473f-94d0-21c30d6601ed">

secretflow/secretnote:1.3.0-amd64

**Comment by aokaokd** [comment]
你好，secretnote目前还没有镜像哈

**Comment by meijiesky** [comment]
> 你好，secretnote目前还没有镜像哈

<img width="921" alt="Screenshot 2024-07-17 at 11 31 57" src="https://github.com/user-attachments/assets/684e2bfe-acfb-42e7-9554-dcc6a6fb1c68">

按照你们文档来的

**Comment by zimu-yuxi** [comment]
dockerhub镜像拉取超时是已知问题。可以使用secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/secretnote:1.6.1-amd64
