### ISSUE TITLE
docker部署问题

### ISSUE THREAD

**Issue by anonymous-PSI-coder** [secretflow/secretnote#52]
国内docker被墙了，请问现在还有什么方式可以拉取secretnote的镜像？

**Comment by aokaokd** [comment]
阿里云可以的：secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/secretnote

**Comment by anonymous-PSI-coder** [comment]
您发送给我的邮件已经收到，我将尽快回复，谢谢！

**Comment by anonymous-PSI-coder** [comment]
> 阿里云可以的：secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/secretnote

非常感谢
